name: "Add calver tag to current checkout branch"

description: "Add a calver style tag to the branch"

inputs:
  who-to-greet:
    description: "Who to greet"
    required: false
    default: "World"

outputs:
  time: # id of output
    description: "The time we greeted you"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}
